import env_file

ALLOWED_HOSTS = env_file.ALLOWED_HOSTS

API_ID = env_file.API_ID
API_HASH = env_file.API_HASH
MAX_UPLOAD_FILE_SIZE_KB = env_file.MAX_UPLOAD_FILE_SIZE_KB
TARGET_SYSTEM_URL = env_file.TARGET_SYSTEM_URL
CONNECT_SESSIONS_ON_RUNSERVER = env_file.CONNECT_SESSIONS_ON_RUNSERVER
