import env_file

ALLOWED_HOSTS = ['127.0.0.1']

API_ID = env_file.API_ID
API_HASH = env_file.API_HASH
MAX_UPLOAD_FILE_SIZE_KB = env_file.MAX_UPLOAD_FILE_SIZE_KB
TARGET_SYSTEM_URL = env_file.TARGET_SYSTEM_URL